### PR TITLE
63 card creator ux

### LINKED ISSUE #88: Artist Artwork Management
It should be possible to find out for which cards one is an artist (in the gallery makes most sense)
and then edit these cards and get to a card creator view, where editing the card artwork is possible

### PR DESCRIPTION
**Pull request by patrickwieth**
this implements #63 
and fixes #88

### CODE REVIEW

**Comment by patrickwieth** [comment]
and sally, if you think this is all, you are wrong! there is even more to it, this fixes #179

**Review by lxgr-linux — CHANGES_REQUESTED** [review]
Bildschirmfoto_2023-02-14_10-20-12
Why so far on the left?

**Comment by patrickwieth** [comment]
> 

good find, please check out update

**Review by lxgr-linux — CHANGES_REQUESTED** [review]
image
Sample gradient image is missing. Would also be a possibility to not use it at all and just show the cropper, when a pic is uploaded.

**Comment by patrickwieth** [comment]
> image Sample gradient image is missing. Would also be a possibility to not use it at all and just show the cropper, when a pic is uploaded.

oh I wonder how this vanished, when I did not touch that. Maybe because of different cropper size. But I think it is better to not have the gradient fun

**Review by lxgr-linux — CHANGES_REQUESTED** [review]
image
After adding the card artwork the artists address appeared in the the address field

**Comment by lxgr-linux** [comment]
Except for that, LGTM

**Comment by lxgr-linux** [comment]
Would also be nice to have an overview on the user view to see for which cards they are the artist. Just like the owned card overview.

**Pull request merged**
