### PR TITLE
204 add more centralized approach to most used state

### LINKED ISSUE #204: Add more centralized approach to most used state
State for:
~~- [ ] Gallery~~
- [x] User

have to be made more centralized to add a more app like feeling to the website.

### PR DESCRIPTION
**Pull request by lxgr-linux**
Centralized coins and user

### CODE REVIEW

**Review by patrickwieth — COMMENTED** [review]
doing stuff like isXYModalVisible over state can sometimes be problematic:
For example in some screen ratios the modal takes up a huge portion of the screen and the close button becomes unclickable, then going back and returning via browser leads to a situation where the modal is still there and might be problematic. I think in this case it might be not too dramatic, since your solution would allow to F5 the page and then get rid of the modal

**Comment by lxgr-linux** [comment]
> doing stuff like isXYModalVisible over state can sometimes be problematic: For example in some screen ratios the modal takes up a huge portion of the screen and the close button becomes unclickable, then going back and returning via browser leads to a situation where the modal is still there and might be problematic. I think in this case it might be not too dramatic, since your solution would allow to F5 the page and then get rid of the modal

Sadly, that's how we did all modals. Always. And I doubt, that other modals via routerlink are possible.

**Comment by patrickwieth** [comment]
It's not necessary to do it via routerlink. The variable can be page specific or be resetted when reloading the page.

**Review by patrickwieth — APPROVED** [review]

**Comment by lxgr-linux** [comment]
That's exactly, what's happening

**Pull request merged**
